apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app-deployment
  labels:
    app: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - name: spring-app
        image: praveensirvi/sprint-boot-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5005

---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
spec:
  selector:
    app: spring-app
  type: NodePort
  ports:
  - name: http
    port: 5005
    targetPort: 5005
    protocol: TCP
    nodePort: 30038
